### ISSUE TITLE
Unpacking issue with IE 

### ISSUE THREAD

**Issue by sud201449** [sapienlab/jsonpack#12]
Hi,
 We are facing issue with upack ok IE browser.  While unpacking its using for..in loop , for...in looks at the array as an object, and therefore properties like indexOf or length may be included in the loop, and failing to decode in IE.

**Comment by roro89** [comment]
Hi, Thanks for noticing this issue. Please, you can give some code example for testing this issue? and if is possible the IE version too. Thanks!

**Comment by sud201449** [comment]
Hi ,
       Issue is happening on IE8 . I couldn't replicate the issue on simple browser setup, but can able to do in our project which is using jquery and require js .

**Comment by candrews** [comment]
See #13
